### ISSUE TITLE
Add Algorithm 

### ISSUE THREAD

**Issue by DaemonOnCode** [riju561/DSAlgo#2]
Heyy
I wish to add algorithms in python. I'd be working on binary tree traversal and lowest common ancestors. Could you please assign me the issue?

**Comment by riju561** [comment]
Go ahead @DaemonOnCode

**Comment by 2devyank** [comment]
I want to add algorithms in java I'd like to work on different types of sorting and searching algorithms. 
Please assign this issue to me

**Comment by riju561** [comment]
Sure, go ahead
