### ISSUE TITLE
Add code for some fundamental data structures

### ISSUE THREAD

**Issue by adityashukzy** [riju561/DSAlgo#4]
I'd like to add code for some basic Data Structures like Linked List, Stacks, Queues, and so on. Does that work?

**Comment by riju561** [comment]
Go ahead @adityashukzy

**Comment by rushendra910** [comment]
@riju561 I would like to add the code for implementing Binary Search Tree in C++. Please assign this to me.

**Comment by riju561** [comment]
> @riju561 I would like to add the code for implementing Binary Search Tree in C++. Please assign this to me.

I have already assigned you on #8 .
