### ISSUE TITLE
Add new questions in C++

### ISSUE THREAD

**Issue by BhavyaKanodia** [riju561/DSAlgo#5]

**Comment by riju561** [comment]
Sure, go ahead

**Comment by lekha06** [comment]
Can I start working on this issue for hackoctober 2021?

**Comment by riju561** [comment]
Sure

**Comment by MohitAswani** [comment]
Can I add DSA questions from GeeksForGeeks?

**Comment by riju561** [comment]
Yes. Just make a new folder named geeksforgeeks in language you are writing.
