### ISSUE TITLE
Add subarray modulo sum cpp question 

### ISSUE THREAD

**Issue by RahulSharma099** [riju561/DSAlgo#6]
Given an array of n elements and an integer m. The task is to find the maximum value of the sum of its subarray modulo m i.e find the sum of each subarray mod m and print the maximum value of this modulo operation.

Sucess Criteria:- 
1. O(nlogn) time complexity

**Comment by RahulSharma099** [comment]
can I work on this issue @riju561 ?

**Comment by riju561** [comment]
Sure, go ahead

**Comment by RahulSharma099** [comment]
Success!
