### ISSUE TITLE
C Data Structures

### ISSUE THREAD

**Issue by nikos-alexandris** [riju561/DSAlgo#9]
Hello, i would like to contribute various data structures in C for hacktoberfest, since i see the C section is pretty empty. Please assign me this issue. Thanks :D

**Comment by nikos-alexandris** [comment]
Update: I will add the following data structures in C:
- Vector
- Stack
- Linked List
- Doubly Linked List
- Queue
- MinHeap
- MaxHeap
- Red-Black Tree

**Comment by riju561** [comment]
Looks great to me, go ahead

**Comment by GO-viper7** [comment]
Hello, @riju561  I would also like to contribute in C for hacktoberfest
data structures apart from the ones which were mentioned by above author :

1. Circular Queue
2. Binary Tree
3. Binary Search Tree

Please assign me to this issue, Thanks.

**Comment by nikos-alexandris** [comment]
I see that someone has already implemented a red black tree, so I'm opening a pull request with the rest.
